"""Views, one for each Insta485 page."""
from insta485.views.index import show_index
from insta485.views.index import show_explore
from insta485.views.index import check_upload
from insta485.views.accounts import post_accounts
from insta485.views.accounts import show_accounts_login
from insta485.views.accounts import post_accounts_logout
from insta485.views.accounts import show_accounts_create
from insta485.views.accounts import show_accounts_delete
from insta485.views.accounts import show_accounts_edit
from insta485.views.accounts import show_accounts_password
from insta485.views.posts import show_posts
from insta485.views.posts import post_posts
from insta485.views.posts import post_likes
from insta485.views.posts import post_comments
from insta485.views.users import show_user
from insta485.views.users import show_followers
from insta485.views.users import show_following
from insta485.views.users import post_following
